name: zwiftdataviewer
description: Zwift Data Viewer

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  http: ^1.0.0
  #  oauth2: ^2.0.0
  url_launcher: ^6.2.5
  intl: ^0.18.1
  path_provider: ^2.1.2
  shared_preferences: ^2.0.13
  # google_maps_flutter: ^0.5.28+1
  # Removed carousel_slider due to conflicts with Flutter's material package
  expandable: ^5.0.1
  flutter_svg: ^2.0.5
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  # Removed flutter_palette dependency which uses problematic flutter_color_models
  syncfusion_flutter_charts: ^22.1.34
  flutter_riverpod: ^2.3.6
  html: ^0.15.3
  flutter_strava_api:
    path: ../stravaapi

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  group_button: ^5.3.3

  stack_trace: any
dev_dependencies:
  flutter_test:
    sdk: flutter

# Override transitive dependencies with compatible versions
dependency_overrides:
  uni_links: ^0.5.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/testjson/activities_test.json
    - assets/testjson/activity_test.json
    - assets/testjson/streams_test.json
    - assets/testjson/photos_test.json
    - assets/zwiftdatalogo.png
  #     - assets/worldcalendar.html

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
