import 'package:zwiftdataviewer/models/climbdata.dart';

enum ClimbId {
  all,
  bealachnaba,
  cheddarGorge,
  cipressa,
  coldaspin,
  coldelaCouillole,
  coldelaMadone,
  coldesAravis,
  colduGalibier,
  colduPlatzerwasel,
  colduRosier,
  colduTourmalet,
  colldOrdino,
  cotedeDomancy,
  cotedePike,
  cotedeTrebiac,
  crowRoad,
  isola2000,
  laLagunaNegra,
  laSuperPlanchedesBellesFilles,
  oldLaHonda,
  oldWillungaHill,
  oudeKwaremont,
  plaDadet,
  poggio,
  puydeDome,
  rocacorba,
  trollstigen,
  others
}

final Map<String, int> climbLookupByName = {
  'Bealach na Bà': 1,
  'Cheddar Gorge': 2,
  'Cipressa': 3,
  "Col d'Aspin": 4,
  'Col de la Couillole': 5,
  'Col de la Madone': 6,
  'Col des Aravis': 7,
  'Col du Galibier': 8,
  'Col du Platzerwasel': 9,
  'Col du Rosier': 10,
  'Col du Tourmalet': 11,
  "Coll d'Ordino": 12,
  'Cote de Domancy': 13,
  'Cote de Pike': 14,
  'Cote de Trebiac': 15,
  'Crow Road': 16,
  'Isola 2000': 17,
  'La Laguna Negra': 18,
  'La Super Planche des Belles Filles': 19,
  'Old La Honda': 20,
  'Old Willunga Hill': 21,
  'Oude Kwaremont': 22,
  "Pla d'Adet": 23,
  'Poggio': 24,
  'Puy de Dome': 25,
  'Rocacorba': 26,
  'Trollstigen': 27,
};

enum climbType {
  basiconly,
  eventonly,
}

final Map<int, ClimbData> allClimbsConfig = {
  1: ClimbData(1, ClimbId.bealachnaba, 'Bealach na Bà',
      'https://zwiftinsider.com/portal/bealach-na-ba/'),
  2: ClimbData(2, ClimbId.cheddarGorge, 'Cheddar Gorge',
      'https://zwiftinsider.com/portal/cheddar-gorge/'),
  3: ClimbData(3, ClimbId.cipressa, 'Cipressa',
      'https://zwiftinsider.com/portal/cipressa/'),
  4: ClimbData(4, ClimbId.coldaspin, "Col d'Aspin",
      'https://zwiftinsider.com/portal/col-daspin/'),
  5: ClimbData(5, ClimbId.coldelaCouillole, 'Col de la Couillole',
      'https://zwiftinsider.com/portal/col-de-la-couillole/'),
  6: ClimbData(6, ClimbId.coldelaMadone, 'Col de la Madone',
      'https://zwiftinsider.com/portal/col-de-la-madone/'),
  7: ClimbData(7, ClimbId.coldesAravis, 'Col des Aravis',
      'https://zwiftinsider.com/portal/col-des-aravis/'),
  8: ClimbData(8, ClimbId.colduGalibier, 'Col du Galibier',
      'https://zwiftinsider.com/portal/col-du-galibier-lautaret/'),
  9: ClimbData(9, ClimbId.colduPlatzerwasel, 'Col du Platzerwasel',
      'https://zwiftinsider.com/portal/col-du-platzerwasel/'),
  10: ClimbData(10, ClimbId.colduRosier, 'Col du Rosier',
      'https://zwiftinsider.com/portal/col-du-rosier/'),
  11: ClimbData(11, ClimbId.colduTourmalet, 'Col du Tourmalet',
      'https://zwiftinsider.com/portal/col-du-tourmalet/'),
  12: ClimbData(12, ClimbId.colldOrdino, "Coll d'Ordino",
      'https://zwiftinsider.com/portal/coll-dordino/'),
  13: ClimbData(13, ClimbId.cotedeDomancy, 'Cote de Domancy',
      'https://zwiftinsider.com/portal/cote-de-domancy/'),
  14: ClimbData(14, ClimbId.cotedePike, 'Cote de Pike',
      'https://zwiftinsider.com/portal/cote-de-pike/'),
  15: ClimbData(15, ClimbId.cotedeTrebiac, 'Cote de Trebiac',
      'https://zwiftinsider.com/portal/cote-de-trebiac/'),
  16: ClimbData(16, ClimbId.crowRoad, 'Crow Road',
      'https://zwiftinsider.com/portal/crow-road/'),
  17: ClimbData(17, ClimbId.isola2000, 'Isola 2000',
      'https://zwiftinsider.com/portal/isola-2000/'),
  18: ClimbData(18, ClimbId.laLagunaNegra, 'La Laguna Negra',
      'https://zwiftinsider.com/portal/la-laguna-negra/'),
  19: ClimbData(
      19,
      ClimbId.laSuperPlanchedesBellesFilles,
      'La Super Planche des Belles Filles',
      'https://zwiftinsider.com/portal/la-super-planche-des-belles-filles/'),
  20: ClimbData(20, ClimbId.oldLaHonda, 'Old La Honda',
      'https://zwiftinsider.com/portal/old-la-honda/'),
  21: ClimbData(21, ClimbId.oldWillungaHill, 'Old Willunga Hill',
      'https://zwiftinsider.com/portal/old-willunga-hill/'),
  22: ClimbData(22, ClimbId.oudeKwaremont, 'Oude Kwaremont',
      'https://zwiftinsider.com/portal/oude-kwaremont/'),
  23: ClimbData(23, ClimbId.plaDadet, "Pla d'Adet",
      'https://zwiftinsider.com/portal/pla-dadet/'),
  24: ClimbData(24, ClimbId.poggio, 'Poggio',
      'https://zwiftinsider.com/portal/poggio/'),
  25: ClimbData(25, ClimbId.puydeDome, 'Puy de Dome',
      'https://zwiftinsider.com/portal/puy-de-dome/'),
  26: ClimbData(26, ClimbId.rocacorba, 'Rocacorba',
      'https://zwiftinsider.com/portal/rocacorba/'),
  27: ClimbData(27, ClimbId.trollstigen, 'Trollstigen',
      'https://zwiftinsider.com/portal/trollstigen/')
};

class Climb {}
